environment:
  PYTHON_ROOT: 'C:\Python37-x64'
init:
  - ps: |
      $ErrorActionPreference = "Stop"
      $env:Path = "$env:PYTHON_ROOT;$env:PYTHON_ROOT\Scripts;$env:Path"
      gcm python
build_script:
  - pip install pyinstaller requests
  - pyinstaller .\easy_install.py --onefile
artifacts:
  - path: dist\*
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: MATLAB Easy Installer $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: UVmFzSqOXDyUnsL8Lx6uSNINMMj454CSH8DapDa/me2/rpyf3swWHu39m4EpYXcj
    artifact: 'dist\easy_install.exe,easy_install.py'
    prerelease: false
    draft: false
    on:
      APPVEYOR_REPO_TAG: true
