environment:
  PYTHON_ROOT: 'C:\Python37-x64'
init:
  - ps: |
      $ErrorActionPreference = "Stop"
      $env:Path = "$env:PYTHON_ROOT;$env:PYTHON_ROOT\Scripts;$env:Path"
      gcm python
build_script:
  - pip install pyinstaller requests
  - pyinstaller .\easy_install.py --onefile
artifacts:
  - path: dist\*
